name: Build Linux

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Vulkan SDK
              uses: humbletim/setup-vulkan-sdk@v1.0.1
              with:
                  vulkan-version: 1.2.170.0
            - name: Install Additional Dependencies
              run: sudo apt-get install libx11-dev libxkbcommon-x11-dev
            - name: Build Linux
              run: cd scripts && chmod +x ./build-all.sh && ./build-all.sh
