name: Build Linux

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install Vulkan SDK
              uses: humbletim/setup-vulkan-sdk@v1.0.1
            - name: Build Linux
              run: cd scripts && chmod +x ./build-all.sh && ./build-all.sh
